version: '3.9'
services:
  mongo:
    image: mongo
    expose:
      - 27017:27017

    volumes:
      - ./mongo-data:/data/db

  yaub:
    build: src/
    env_file:
      - Yaub.env

volumes:
  mongo-data: